@SimpleApi_HostAddress = https://localhost:7275


### Login
### use this to get an access token - take if from the response
### and paste it into the {{access_token}} variable below
POST https://demo.duendesoftware.com/connect/token
Content-Type: application/x-www-form-urlencoded

client_id=m2m&client_secret=secret&grant_type=client_credentials&scope=api

###
@token=eyJhbGciOiJSUzI1NiIsImtpZCI6IkMyNTJGOUNBQjc3Q0MxNTQwNTBFMTg1NTk5MjJCMTJGIiwidHlwIjoiYXQrand0In0.eyJpc3MiOiJodHRwczovL2RlbW8uZHVlbmRlc29mdHdhcmUuY29tIiwibmJmIjoxNzA2NTg4MDUxLCJpYXQiOjE3MDY1ODgwNTEsImV4cCI6MTcwNjU5MTY1MSwiYXVkIjoiYXBpIiwic2NvcGUiOlsiYXBpIl0sImNsaWVudF9pZCI6Im0ybSIsImp0aSI6IjJCNTJBNkJGOTIzRkEzRjhDMDA3QTQ5OEY2M0I2MjExIn0.ihduJ1hjtILtKNDjCTqdtloKb1gpKC5HlJ0UY9PknCXtY5MYh8mpZ8NUrkaV9G97o5kqHRKxMlNzLujjDknzOIug1-PdIzIfN7VP0P1o9XnA9dO_XP44zYYyJFV8DdOE-ZOYQoIdsCUCUibMIs0fAPODimT4tjg0m8hh51kN-L8lTpAUGpl_Ju_wTtI16A9DqoJw-mDJwBGpFUJ4WimwYEwUo2tht153uYp4Ls0tkRju60AXIy-PlBWpW0BfOapXDZodPGOE7ZTkQSbm3SeN5zJOi0zs93Sf63CZEji6rUOBxMTEWxWb433uOPkpcN3CNzJNPDk0sojw49UIMbWw3Q

###

GET {{SimpleApi_HostAddress}}/weatherforecast?postalCode=55125
Accept: application/json
Authorization: Bearer {{token}}

###

GET {{SimpleApi_HostAddress}}/v1/products
Accept: application/json
Authorization: Bearer {{token}}

###

GET {{SimpleApi_HostAddress}}/v1/products?category=Books
Accept: application/json

###

GET {{SimpleApi_HostAddress}}/v1/products/3
Accept: application/json

###

GET {{SimpleApi_HostAddress}}/v1/products/999 
Accept: application/json

###


POST {{SimpleApi_HostAddress}}/v1/products
Content-Type: application/json

{
    "name": "macguffin",
    "description": "a thing that does stuff",
    "category": "",
    "price": 1.00,
    "imgUrl": "https://some.place/wow.png"
}

###

POST {{SimpleApi_HostAddress}}/v1/products
Content-Type: application/json

{
    "name": "macguffin",
    "description": "a thing that does stuff",
    "category": "equip",
    "price": 1.00,
    "imgUrl": "https://some.place/wow.png"
}

###

GET {{SimpleApi_HostAddress}}/weatherforecast?postalCode=525
Accept: application/json

###


GET {{SimpleApi_HostAddress}}/weatherforecast?postalCode=error
Accept: application/json