@SimpleApi_HostAddress = https://localhost:7275


### Login
### use this to get an access token - take if from the response
### and paste it into the {{access_token}} variable below
POST https://demo.duendesoftware.com/connect/token
Content-Type: application/x-www-form-urlencoded

client_id=m2m&client_secret=secret&grant_type=client_credentials&scope=api

###
@token=eyJhbGciOiJSUzI1NiIsImtpZCI6IkMyNTJGOUNBQjc3Q0MxNTQwNTBFMTg1NTk5MjJCMTJGIiwidHlwIjoiYXQrand0In0.eyJpc3MiOiJodHRwczovL2RlbW8uZHVlbmRlc29mdHdhcmUuY29tIiwibmJmIjoxNzA2MDk5MzM5LCJpYXQiOjE3MDYwOTkzMzksImV4cCI6MTcwNjEwMjkzOSwiYXVkIjoiYXBpIiwic2NvcGUiOlsiYXBpIl0sImNsaWVudF9pZCI6Im0ybSIsImp0aSI6IjJENzYyQUNGMTFCMTM2NkJBQzA1RDQ1ODk4QzMyMjlGIn0.oglIZpaLr9n0Tr2pcT-y5Ba9ggP_pR8iakdLIOk-IURaOeBWY4_VA42MRfrfsQ7Zyh0V7Z5v6lwAeK3ACUEAFgB0KrQcdqwuhOUTN6CylQgfaP-2-GdDczMCdP2XAbsjz6yVXVZ6ZPai1m0K8cB7ToveJpl5YE9Dfc2dZgvkkL3WsQ5-3DJTa78BjvRMNYcA1wVz_jwpWcq4H4GzNKoseeNe1ocdeseVpAtbMnAo3_Rc7nXx18W_ThkRrUFW8Wk3hegx-7kZJz3cCxod9cl4bj6QpXbwdr-6t9j8xnQ82X-d2A5kqwdOjvHGBhgrfjWsfqtMFxuzIKTixP-TXL3Alw

###

GET {{SimpleApi_HostAddress}}/weatherforecast?postalCode=55125
Accept: application/json
Authorization: Bearer {{token}}

###

GET {{SimpleApi_HostAddress}}/v1/products
Accept: application/json
Authorization: Bearer {{token}}

###

GET {{SimpleApi_HostAddress}}/v1/products?category=Books
Accept: application/json

###

GET {{SimpleApi_HostAddress}}/v1/products/3
Accept: application/json

###

GET {{SimpleApi_HostAddress}}/v1/products/999 
Accept: application/json

###


POST {{SimpleApi_HostAddress}}/v1/products
Content-Type: application/json

{
    "name": "macguffin",
    "description": "a thing that does stuff",
    "category": "",
    "price": 1.00,
    "imgUrl": "https://some.place/wow.png"
}

###

POST {{SimpleApi_HostAddress}}/v1/products
Content-Type: application/json

{
    "name": "macguffin",
    "description": "a thing that does stuff",
    "category": "equip",
    "price": 1.00,
    "imgUrl": "https://some.place/wow.png"
}

###

GET {{SimpleApi_HostAddress}}/weatherforecast?postalCode=525
Accept: application/json

###


GET {{SimpleApi_HostAddress}}/weatherforecast?postalCode=error
Accept: application/json